
name: Node.js CI

on:
  push:
    branches: [ "pegah" ]
  pull_request:
    branches: [ "pegah" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
